---
name: Map request
description: Create a map
title: "[name of your map request]"
body:
- type: input
  id: latitude
  attributes:
    label: Latitude
    description: "Map center latitude"
    placeholder: "Example: 44.590278"
  validations:
    required: true
- type: input
  id: longitude
  attributes:
    label: Longitude
    description: "Map center longitude"
    placeholder: "Example: -104.715278"
  validations:
    required: true
- type: dropdown
  id: default_style
  attributes:
    label: Default Map Style
    description: Map style to use by default
    options:
      - light-v11
      - dark-v11
      - streets-v12
      - outdoors-v12
      - satellite-v9
      - satellite-streets-v12
    default: 2
  validations:
    required: true
- type: dropdown
  id: light_style
  attributes:
    label: Light Mode Map Style
    description: Map style to use in light mode
    options:
      - light-v11
      - dark-v11
      - streets-v12
      - outdoors-v12
      - satellite-v9
      - satellite-streets-v12
  validations:
    required: false
- type: dropdown
  id: dark_style
  attributes:
    label: Default Map Style
    description: Map style to use in dark mode
    options:
      - light-v11
      - dark-v11
      - streets-v12
      - outdoors-v12
      - satellite-v9
      - satellite-streets-v12
  validations:
    required: false
---


